# 최상단(루트)에 위치시킵니다.
jwt:
  secret: ${JWT_SECRET:eyJhbGciOiJIUzUxMiJ9.ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNk1UQXhOak0xTmpZMU1tRTFOamszTkRNeU5qRXpOak01TkRRMU16a3hNbUUzIn0}
  expiration-ms: 
      access: 3600000    # 1시간 (밀리초)
      refresh: 604800000 # 7일 (밀리초)

spring:
  profiles:
    active: dev
  web:
    cors:
      mappings:
        /api/**:
          allowed-origins: "http://localhost:3000"
        /ws/**:
          allowed-origins: "http://localhost:3000"      
  datasource:
    url: jdbc:mysql://localhost:3306/specup_project?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: specup_user
    password: SpecupPass123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: never

server:
  port: 8081

  springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

